



import { Ubuntu } from "next/font/google";
import "../globals.css";
import Header from "./H&F/Header/Header";
import Footer from "./H&F/Header/Footer";
import { Providers } from "../PRO/Providers";



const geistSans = Ubuntu({
  weight: ["400", "500", "700",],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable}  antialiased`}
      >


        <div className="font-ubuntu">

          <Providers  >

            <Header></Header>
            {children}
            <Footer></Footer>
          </Providers>

        </div>

      </body>
    </html>
  );
}

