import {
  Rubik

} from "next/font/google";
import "../globals.css";


import { Providers } from "../PRO/Providers";

import Header2 from "./Componenets/Fixed/Header/Header2";
import Footer from "./Componenets/Fixed/Footer";




const geistSans = Rubik({
  weight: ["400", "500", "300", "700", "600", "800", "900"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable}  antialiased`}
      >

        <div className="font-stack">



         <Providers>

          <Header2></Header2>
          {children}
         
          <Footer></Footer>
          </Providers>

            


        </div>
      </body>
    </html>
  );
}
